Added the screenshots and updated the readme screenshots
Ngoakor12/coding-resource-finder pull request #125
Opened 2022-10-02 09:13 UTC by Shivashish-rwt

## 🛠️ Fixes issue(s)

Closes #116 

## 👨‍💻 Change(s) proposed

Added the updated the screenshots in `README.md` and added the Screenshots in `./docs/SCREENSHOTS.md`

## ✔️ Checklist (Check all the applicable boxes) 

- [x ] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2022-10-02 09:13 UTC, Shivashish-rwt commented
@Ngoakor12 
Please review the PR.

2022-10-04 03:53 UTC, Ngoakor12 requested changes
Thanks you for open a PR and being patient, here are my thoughts...
- One big thing, The screenshots to the previous site should not be added, I think the links is enough and anything more than that seems like I'm taking a dig at it.
- The `screenshots.md` file is in the wrong place, create a folder on the root named `docs` and create a `screenshot.md` file inside, you may also add the `.png` files in a `screenshots` folder inside `docs` folder
- In the `readme.md` in in the root, add a screenshot of the resources page and bookmarks page under the `screenshots` heading, and also link the the screenshots.md file with something like..."More screenshots" text
- Screenshots folder name should be all lowercase to keep everything consistent.

2022-10-04 04:53 UTC, Shivashish-rwt commented
@Ngoakor12 
I have made the changes as u told. Please let me know if more changes required.

2022-10-04 05:11 UTC, Ngoakor12 requested changes
- Move the `screenshots.md` from `./backend/src/docs` to `./docs`
- There still some screenshots pngs from the original ACN website
- `./screenshots` folder should be in the `./docs` folder

2022-10-04 06:33 UTC, Shivashish-rwt commented
@Ngoakor12 
Please review.

2022-10-04 07:14 UTC, Ngoakor12 requested changes
Almost there, just one tiny thing you've missed twice...
You should not touch the backend folder. **The `SCREENSHOTS.md` file that's in the `./backend/src/docs` folder should be move to the `./docs` folder you created in the root of the project**

2022-10-05 05:02 UTC, Shivashish-rwt commented
@Ngoakor12 
Moved the `SCREENSHOTS.md` to `./docs`. Please check.

2022-10-05 05:32 UTC, Ngoakor12 requested changes

2022-10-05 05:32 UTC, Ngoakor12 commented on README.md
> +[More screenshots](./docs/screenshots/)
please link to the `SCREENSHOTS.md` instead of the screenshots images folder for the "More screenshot" link

2022-10-05 05:45 UTC, Shivashish-rwt commented
@Ngoakor12 
Linked `SCREENSHOTS.md`.

2022-10-05 05:52 UTC, Ngoakor12 commented
Much better, thanks for the contribution @Shivashish-rwt

2022-10-05 05:53 UTC, Ngoakor12 approved these changes

2022-10-05 05:53 UTC, merged

2022-10-05 05:54 UTC, Shivashish-rwt commented
@Ngoakor12 
Thanks for giving me opportunity to contribute.
This is my first time contributing to open source.  Could u give me some advice or anything i need to learn in order to become better??

2022-10-05 06:04 UTC, Ngoakor12 commented
> @Ngoakor12 Thanks for giving me opportunity to contribute. This is my first time contributing to open source. Could u give me some advice or anything i need to learn in order to become better??

- Don't work on the master branch of the branch you forked, rather create a separate branch
- And take time to understand the issue and read feedback carefully, because you did miss a lot of stuff, but what matters is you got there in the end :+1:

2022-10-05 06:14 UTC, Shivashish-rwt commented
Thanks for advice.